ckan_module.settings:
  type: config_object
  label: 'CKAN Module settings'
  mapping:
    ckan_module:
      type: mapping
      mapping:
        ckan_api:
          type: text
          label: 'CKAN API URL:'
        ckan_key:
          type: text
          label: 'CKAN API Key:'
block.settings.ckan_module_block:
  type: block_settings
  label: 'CKAN Module block'
  mapping:
    ckan_module_block_settings:
      type: text
      label: 'CKAN Module block settings'